# Projection of the incan.pub event log; regenerate with `incan-pub build`, never edit.

[project]
name = "crates-io/ra-ap-rustc_index"
version = "0.143.0"

[project.features]
nightly = []
rustc_randomized_layouts = []

[rust]
name = "ra_ap_rustc_index"
type = "lib"
edition = "2024"
build-script = false

[dependencies]
rustc_index_macros = { loaf = "crates-io/ra-ap-rustc_index_macros", version = "^0.143.0" }
