# Projection of the incan.pub event log; regenerate with `incan-pub build`, never edit.

[project]
name = "crates-io/ra_ap_paths"
version = "0.0.325"

[project.features]
serde1 = ["camino/serde1"]

[rust]
name = "ra_ap_paths"
type = "lib"
edition = "2024"
build-script = false

[dependencies]
camino = { loaf = "crates-io/camino", version = "^1.2.2" }
