# Projection of the incan.pub event log; regenerate with `incan-pub build`, never edit.

[project]
name = "crates-io/elliptic-curve"
version = "0.13.8"

[project.features]
alloc = ["base16ct/alloc", "ff?/alloc", "group?/alloc", "pkcs8?/alloc", "sec1?/alloc", "zeroize/alloc"]
arithmetic = ["group"]
bits = ["arithmetic", "dep:ff", "ff/bits", "dep:tap"]
default = ["arithmetic"]
dev = ["arithmetic", "dep:hex-literal", "pem", "pkcs8"]
digest = ["dep:digest"]
ecdh = ["arithmetic", "digest", "dep:hkdf"]
ff = ["dep:ff"]
group = ["dep:group", "ff"]
hash2curve = ["arithmetic", "digest"]
hazmat = []
jwk = ["dep:base64ct", "dep:serde_json", "alloc", "serde", "zeroize/alloc"]
pem = ["dep:pem-rfc7468", "alloc", "arithmetic", "pkcs8", "dep:sec1", "sec1/pem"]
pkcs8 = ["dep:pkcs8", "sec1"]
sec1 = ["dep:sec1"]
serde = ["dep:serdect", "alloc", "pkcs8", "dep:sec1", "sec1/serde"]
std = ["alloc", "rand_core/std", "pkcs8?/std", "sec1?/std"]
voprf = ["digest"]

[rust]
name = "elliptic_curve"
type = "lib"
edition = "2021"
build-script = false

[dependencies]
base16ct = { loaf = "crates-io/base16ct", version = "^0.2" }
base64ct = { loaf = "crates-io/base64ct", version = "^1", features = ["alloc"], default-features = false, optional = true }
crypto-bigint = { loaf = "crates-io/crypto-bigint", version = "^0.5", features = ["generic-array", "rand_core", "zeroize"], default-features = false }
digest = { loaf = "crates-io/digest", version = "^0.10", optional = true }
ff = { loaf = "crates-io/ff", version = "^0.13", default-features = false, optional = true }
generic-array = { loaf = "crates-io/generic-array", version = "^0.14.6", features = ["zeroize"], default-features = false }
group = { loaf = "crates-io/group", version = "^0.13", default-features = false, optional = true }
hex-literal = { loaf = "crates-io/hex-literal", version = "^0.4", optional = true }
hkdf = { loaf = "crates-io/hkdf", version = "^0.12.1", default-features = false, optional = true }
pem-rfc7468 = { loaf = "crates-io/pem-rfc7468", version = "^0.7", features = ["alloc"], optional = true }
pkcs8 = { loaf = "crates-io/pkcs8", version = "^0.10.2", default-features = false, optional = true }
rand_core = { loaf = "crates-io/rand_core", version = "^0.6.4", default-features = false }
sec1 = { loaf = "crates-io/sec1", version = "^0.7.1", features = ["subtle", "zeroize"], optional = true }
serde_json = { loaf = "crates-io/serde_json", version = "^1.0.47", features = ["alloc"], default-features = false, optional = true }
serdect = { loaf = "crates-io/serdect", version = "^0.2", features = ["alloc"], default-features = false, optional = true }
subtle = { loaf = "crates-io/subtle", version = "^2", default-features = false }
tap = { loaf = "crates-io/tap", version = "^1.0.1", default-features = false, optional = true }
zeroize = { loaf = "crates-io/zeroize", version = "^1.7", default-features = false }
