# Projection of the incan.pub event log; regenerate with `incan-pub build`, never edit.

[project]
name = "crates-io/snafu"
version = "0.9.2"

[project.features]
alloc = []
backtrace = []
backtraces-impl-backtrace-crate = ["dep:backtrace"]
default = ["std", "rust_1_81"]
futures = ["dep:futures-core", "dep:pin-project"]
futures-core-crate = []
futures-crate = []
guide = []
internal-dev-dependencies = ["dep:futures"]
pin-project = []
rust_1_81 = []
std = ["alloc"]
unstable-provider-api = ["snafu-derive/unstable-provider-api"]
unstable-try-trait = []

[rust]
name = "snafu"
type = "lib"
edition = "2018"
build-script = false

[dependencies]
backtrace = { loaf = "crates-io/backtrace", version = "^0.3.0", features = ["std"], default-features = false, optional = true }
futures = { loaf = "crates-io/futures", version = "^0.3.11", features = ["executor"], default-features = false, optional = true }
futures-core = { loaf = "crates-io/futures-core", version = "^0.3.0", default-features = false, optional = true }
pin-project = { loaf = "crates-io/pin-project", version = "^1.0.2", default-features = false, optional = true }
snafu-derive = { loaf = "crates-io/snafu-derive", version = "^0.9.2" }
